### ISSUE TITLE
Как получать данные?

### ISSUE THREAD

**Issue by westprophet** [Ozerich/yii2-filestorage-db#1]
Я не могу достать ссылку. 

Сохранить файл по вашей инструкции с сохранением в бд, я то это сделал, но не могу никак получить эти данные из бд в виде хотя бы ссылки.

По ковырявшись в вашем коде, я попытался использовать File модель, а именно метод getUrl() но он не работает, выдает ошибку что сценарий 'Avatar' не найден. Так как его действительно нет при отладке кода я проверил переменную scenarios и ничего не обнаружил.

Пробовал достать запросом в БД но те данные не возможно использовать без костылей. Да и что то не правильно, предназначалось ли это к этому виду использования - я сомневаюсь. Методы в модели есть но они не работают.

Метода в Component я не нашел который возвращает например ту же модель File или создает её. 

Я не могу понять для чего предназначался данный компонент? Просто хранить данные из бд? Или же есть где то ошибка? Как им пользоваться? Вроде задумка простая и мне нравится но все же не могу использовать на полную мощность подскажите как и оставьте пару примеров как получать из базы эти данные.

**Comment by Ozerich** [comment]
Надо добавить компонент в bootstap

config.php

{
...
'bootstrap' => ['media']
...
}
